### ISSUE TITLE
请求增加`GEOSITE,geolocation-!cn`分类

### ISSUE THREAD

**Issue by yueisme** [DustinWin/ruleset_geodata#30]
希望能提供`GEOSITE,geolocation-!cn`分类，README提到此项目上游数据来自 https://github.com/Loyalsoldier/v2ray-rules-dat ，起因是我目前在尝试使用 https://wiki.metacubex.one/example/conf/ 的配置方法，这样可以免于维护各种 fake-ip-filter 的内网域名，对于这种配置方式`GEOSITE,geolocation-!cn`分类是不可缺少的一部分。

```yaml
#我的部分配置片段
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

dns:
  nameserver:
    - system
  fake-ip-filter:
    - "+.*"
  nameserver-policy:
    "geosite:cn": system
    "geosite:apple-cn": system
    "geosite:microsoft-cn": system
    #"rule-set:google-cn": system # MetaCubeX/meta-rules-dat不提供google-cn
    "geosite:geolocation-!cn":
    - 'https://cloudflare-dns.com/dns-query#Proxy'
    - 'tls://dns.google#Proxy'
```

这样做比较依赖精细配置的规则，我对比过后发现本项目的规则更精细一些，但是目前`nameserver-policy`不能支持`RULE-SET`匹配，如果有`GEOSITE,geolocation-!cn`就可以在 mihomo 的 DNS 模块使用了。
